\begin{figure}
\centering
\begin{subfigure}{0.32\columnwidth}
    \includegraphics[width=1\textwidth]{images/chapter4/clover-render-confA.png}
    \caption{Rendering Workloads A and C (camera positioned inside the data set)}
\end{subfigure}
\begin{subfigure}{0.32\columnwidth}
    \includegraphics[width=1\textwidth]{images/chapter4/clover-render-confB.png}
    \caption{Rendering Workload B (camera positioned near the data set)}
\end{subfigure}
\begin{subfigure}{0.32\columnwidth}
    \includegraphics[width=1\textwidth]{images/chapter4/clover-render-confD.png}
    \caption{Rendering Workload D (camera positioned far from the data set)}
\end{subfigure}
\caption[Rendered images of the CloverLeaf data set from three different
camera positions.]{\label{fig:cloverrenders}Rendered images of the data set from the
three camera positions used in this study --- inside, near, and far.
%
The renderings show a pressure wave expanding from the corner of the data set
where the initial energy was deposited.
}
\end{figure}
